### ISSUE TITLE
Access v-text-field slots

### ISSUE THREAD

**Issue by toddb** [MadimetjaShika/vuetify-google-autocomplete#107]
## Is your feature request related to a problem?
I need access to the text field scopes (eg append) in the field so that I can style it like all my other fields in the form.

## Describe the solution you'd like
I would like to be able to access the slots in the textfield (ie append). There are actually seven.

## Describe alternatives you've considered
Sorry, I can't see another way (eg using the $ref) that is straightforward (ie without extending the inserting)

## Additional context
Having looked at the code, I can't see that any of the v-text-field slots are proxied yet all events and props are.

Here is an example of how I would like to use "append" on the text-field.

```html
<vuetify-google-autocomplete
    id="map"
    append-icon="search"
    v-bind:disabled="true"
    placeholder="Start typing"
    v-on:placechanged="getAddressData"
>
        <template #append>
               ... my content
        </template>
</vuetify-google-autocomplete>
```

**Comment by toddb** [comment]
Just been looking at a solution for adding templates as part of a render function. This approach is tied to a particular implementation of `v-text-field` and could dynamically check slots. However, it would then need to kebab case the slots.

Based on https://forum.vuejs.org/t/how-to-pass-named-slots-to-child-component-via-render-function/40842 

Here's a patch file

```patch
Index: src/vga/VuetifyGoogleAutocomplete.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/vga/VuetifyGoogleAutocomplete.js	(revision d033f41b13d53b6d054ff99da0c8212b9d9de50d)
+++ src/vga/VuetifyGoogleAutocomplete.js	(date 1594631262374)
@@ -950,7 +950,8 @@
       // Override the default placeholder
       // text set by Google with the
       // placeholder prop value or an empty value.
-      document.getElementById(this.id).setAttribute('placeholder', this.placeholder ? this.placeholder : '');
+      document.getElementById(this.id)
+        .setAttribute('placeholder', this.placeholder ? this.placeholder : '');
 
       this.autocomplete.addListener('place_changed', () => {
         const place = this.autocomplete.getPlace();
@@ -1162,7 +1163,17 @@
           this.autocompleteText = value;
         },
       },
-    }, []);
+    },
+    [
+      'append',
+      'append-outer',
+      'label',
+      'message',
+      'prepend',
+      'prepend-inner',
+      'progress',
+    ]
+      .map(slot => createElement('template', { slot }, [this.$slots[slot]])));
   },
   /**
    * @mixin

```

**Comment by MadimetjaShika** [comment]
Hi @toddb, thanks for the PR. Will publish a patch version shortly.

**Comment by toddb** [comment]
Thanks. Looking forward to the patch version! (it will go straight into our product).

I can add page to the examples (personally, I not sure I would but I needed a "test").

It could do with documentation. Let me know about either and will make changes and pull request.

**Comment by MadimetjaShika** [comment]
New version published to npm registry, `vuetify-google-autocomplete@2.0.2`. Thanks again.

Yes sure a usage example would be great. I think if you could add something to the README that would be great for now. I'd like to update the example app and the dependencies on this project as most of them are now version outdated. So I'll update the example app when I do the clean-up exercise.

**Comment by toddb** [comment]
The `messages` slot is a scoped slot and is not implemented correctly. As such, it is not included in the documentation.

It should be upgraded (or removed).
