### ISSUE TITLE
How to use with vuetify Simple HTML template?

### ISSUE THREAD

**Issue by skwigs** [MadimetjaShika/vuetify-google-autocomplete#11]
I'm working on an app that will be embedded in an existing website. Since I'm not using webpack, I keep running into 'unexpected token import/export' errors - no matter how I split the code up or try to import it to my app.

Any thoughts on an html/non-npm setup? What needs to go where?

**Comment by MadimetjaShika** [comment]
Hi there! Sorry I saw your post a while back, just haven't had a chance to look into it yet. I should get a chance to look into it before Friday, will get back to you soon.

**Comment by MadimetjaShika** [comment]
Hi there @skwigs, sorry i've taken so long to get to this. Could you please provide me with a code sample of your current setup?

**Comment by MadimetjaShika** [comment]
Hi there. This issue should now be fixed. The problem was that the component was exported as ES6 and not ES5, which meant that to use it you needed to have some loader that could read ES6 or a transpiler to transpile the code from ES6 to ES5 before usage.

**Comment by MadimetjaShika** [comment]
PS - let me know if you still experiencing any issues.
