### ISSUE TITLE
Feature Request: setting default value

### ISSUE THREAD

**Issue by rolandszpond** [MadimetjaShika/vuetify-google-autocomplete#12]
Passing a prop down to set the initial value on the input. Oddly, it's not listed in the API documentation for the component, but it's used within the examples.

**Comment by MadimetjaShika** [comment]
Hi @rolandszpond. Thanks for noting that. I'll look into it this coming weekend. Ideally i'd like to rewrite this library as most of it was written on top of forked code. I noticed several "issues" that prevent/disturb reactivity with the way it is currently written. I'll let you know as soon as it is sorted.

**Comment by MadimetjaShika** [comment]
Hi @rolandszpond,

Thanks for posting this. I do apologise in having taken forever to resolve this issue. This is now resolved in the [latest release v2.0.0-alpha.5](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases). So you should now be able to pass down a ``v-model`` value as a default value for the text field.

Do feel free to re-open this issue if you still experience any issues.
