### ISSUE TITLE
Api key requested as prop in the aplha version

### ISSUE THREAD

**Issue by iec989** [MadimetjaShika/vuetify-google-autocomplete#16]
I would like to know what's the best approach to pass the API key only once? Right now every time I'm invoking the component I'm passing the API key prop. This gives an error if you try to have more than one input.

I did the below to make it work, but I don't think that's what is intended with your code:
`VuetifyGoogleAutocomplete.props.googleApiKey = {type: String, default: 'myapikey'};
Vue.component('vuetify-google-autocomplete', VuetifyGoogleAutocomplete);`

And I still get the error below if I use more than one autocomplete in the same page:
_You have included the Google Maps API multiple times on this page. This may cause unexpected errors._

Thanks!

**Comment by iec989** [comment]
@MadimetjaShika 

Any update on this?

Thanks

**Comment by MadimetjaShika** [comment]
Hi,

Sorry I haven't had a chance to _properly_ resolve this issue. I have however looked at it briefly. I'll make some time to resolve it before the end of the week.

I think a solution could be to pass the key only once, however subsequent asynchronous usages of the component will complain that the Google API has not been initialised. I'm somewhat tempted to make the API key optional, and in the case that it's not provided, rely upon the parent component or application to actually initialise it. This is not ideal, however i'm struggling to see a better way around this. Suggestions are more than welcome.

If you do have some suggestions or you are able to resolve it, feel free to make a PR. Alternatively, you can expect a fix release sometime later during the week.

**Comment by MadimetjaShika** [comment]
Hi there.

This issue should now be resolved. Please refer to the [latest release notes](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases) on usage changes.

As noted on the release notes, you _might_ still experience issues if you try to use this component with a different vue component that also loads the Google API. I haven't yet built to cater for that.

Again, I do apologise for taking so long to resolve this. Please do let me know if you still experience any problems.

Thanks again for pointing this issue out!

**Comment by iec989** [comment]
Thank you very much mate - working like a charm

**Comment by phaberest** [comment]
Hi @MadimetjaShika, is there a way to avoid the load entirely and just keep the key for the requests? I'm using another component to show a map and it is conflicting as both load the google maps js
