### ISSUE TITLE
hideDetails Prop has wrong default value (should be false)

### ISSUE THREAD

**Issue by benjaminpwarren** [MadimetjaShika/vuetify-google-autocomplete#17]
The `hideDetails` prop in the component is currently set to a default of `true` whereas the Vuetify standard <v-text-field> has a default of `false`.

I had to hunt down why my error message (triggered via the `:rules` prop) wasn't showing, and it was this prop.

**Comment by MadimetjaShika** [comment]
Hi @benjaminpwarren!

Thanks for pointing this out. A previous commit made actually changed the default value from false to true, which shouldn't have happened. I have resolved this in [the latest release](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases) though.

Thanks for pointing this out. I do apologise for taking so long to get to this. Do let me know if you still experience any issues.
