### ISSUE TITLE
How to repopulate the input field when loading the form

### ISSUE THREAD

**Issue by jess8bit** [MadimetjaShika/vuetify-google-autocomplete#19]
Hello, 
I use this Vue component in a create/edit form (using Vuetify v1.0.1).
In "edit" mode, when display the form, I would like to be able to repopulate the input field with any string (typically what the user entered last time but that is just a example).
The input value is handled by the autocompleteText data of the component, but how can I set a value to this field, programmatically, for example in a created or mounted hook, or any component method?

Thanks a lot for your help :)

**Comment by MadimetjaShika** [comment]
Hi @jess8bit,

Thanks for posting the issue. This has been resolved in the latest release. So any v-model you pass to the component should behave as expected. Please refer to the [latest release notes](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases) for changes.

Thanks again!

**Comment by jess8bit** [comment]
Thanks for the update!
