### ISSUE TITLE
prepend-icon not working

### ISSUE THREAD

**Issue by mwargan** [MadimetjaShika/vuetify-google-autocomplete#20]
Hey! I'm not able to use prepend-icon. Changing prepend to append works as expected, and the icon is appended. It just doesn't want to prepend.

`prepend-icon="location_on"`

No error is showing in the console.

What could I be doing wrong here?

**Comment by MadimetjaShika** [comment]
Hi @mwargan,

Seems there was a typo in the code that resulted in this bug. I have resolved this in[ the latest release](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases).

Please do let me know if you still experience any issues.

Thanks again!
