### ISSUE TITLE
How to populate a value from the server?

### ISSUE THREAD

**Issue by maxcook** [MadimetjaShika/vuetify-google-autocomplete#22]
So i use this awesome component to create and edit a model. So in the creation form it all works like a charm. However, in the edit form i would like to populate the current value of the model into the vuetify-google-autocomplete
I tried :value, v-model and the $refs.address.update() to set the initial value to the field but it doesnt work at all. Any ideas?

**Comment by MadimetjaShika** [comment]
Hi @maxcook,

This issue should now be resolved in [the latest release](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases).  So any v-model you pass to the component should behave as expected.

Do let me know if you still experience any issues

Thanks!
