### ISSUE TITLE
Can we use hint?

### ISSUE THREAD

**Issue by mwargan** [MadimetjaShika/vuetify-google-autocomplete#23]
I tried to use `:hint` or `hint`, but neither seemed to work. Any simple solution to implement that?

**Comment by MadimetjaShika** [comment]
hi @mwargan,

Thanks for posting this. This prop was introduced in a later version of Vuetify which was not yet supported by this component. I have however updated the component to support Vuetify v1.0.3 which is the latest at the time of writing this post. So you can now pass ``:hint`` and it will behave as expected. See the [latest release notes on v2.0.0-alpha.4](https://github.com/MadimetjaShika/vuetify-google-autocomplete/releases).

Do let me know if you experience any issues. Thanks again!
