### ISSUE TITLE
Returning ISO country value

### ISSUE THREAD

**Issue by mwargan** [MadimetjaShika/vuetify-google-autocomplete#24]
Hello!

Is it possible to return the ISO code of the country, instead of / with a country name?

**Comment by MadimetjaShika** [comment]
Hi @mwargan,

I'm not too certain what you mean by your question. The component returns the result from Google Places call via the ``:placechanged="..."`` event. The handler function will be passed three parameters;
* ``returnData`` - Which is just a re-formatted version of the result object returned from the Google API call, 
* `` place`` - Which is the exact and full (unmodified) result  object returned by the Google API call, and
* ``id``  - Which is the ID of the component that triggered this call (in case you are using this component multiple times on the same page/project)

You can use the ``place`` parameter to obtain the ISO code of the country, which should be the ``short_name`` of the ``address_components`` containing ``"types" : [ "country", "political" ]`` according to the [Google places API docs](https://developers.google.com/places/web-service/details). The full country name would then be contained within the ``long_name`` property.

I'm closing this issue for now, feel free to re-open the issue if I have not answered your question or if you still need help.
