### ISSUE TITLE
NPM update reverts to "2.0.0-alpha.1.test.3"

### ISSUE THREAD

**Issue by timothynott** [MadimetjaShika/vuetify-google-autocomplete#32]
*Steps to reproduce:*
- npm update vuetify-google-autocomplete

package.json now lists the package as "^2.0.0-alpha.1.test.3"

*Steps to fix:*
- npm remove vuetify-google-autocomplete
- npm install vuetify-google-autocomplete

**Comment by timothynott** [comment]
This is still happening to me.
Is anyone else seeing this behavior?

**Comment by MadimetjaShika** [comment]
Hey @timothynott 

I noticed the issue too. I asked the folks at NPM to delete the version from the registry however they could not do so. However as soon as a Beta or official v2 is released the problem should be gone, which I think should be soon as it seems most of the fundamental issues have been identified and addressed already in the Alpha versions. I'd just like to bring unit tests back to the component before that though.

**Comment by MadimetjaShika** [comment]
Resolved. NPM is sensitive to version naming, so the capitalisation of the "B" in "Beta" or "A" in "Alpha" causes confusion. Versions are now strictly lower cased. ``npm update`` should now always return the latest version as expected.

Please let me know if anyone still experiences the problem.
