### ISSUE TITLE
Which version is in the demo?

### ISSUE THREAD

**Issue by project-orcon** [MadimetjaShika/vuetify-google-autocomplete#44]

**Comment by MadimetjaShika** [comment]
Hi, I just updated the demo to use the latest version ``2.0.0-Alpha.9``. An older version was running (likely ``2.0.0-Alpha.8``). Thanks for pointing that out.

**Comment by MadimetjaShika** [comment]
@project-orcon  I've published a new release with a few fixes, ``2.0.0-Beta.2``.

**Comment by project-orcon** [comment]
Thanks for the fantastic library!
