### ISSUE TITLE
Validation doesn't work

### ISSUE THREAD

**Issue by kstraszewski** [MadimetjaShika/vuetify-google-autocomplete#45]
Hi I have a problem with validation on blur, i would like to validate vuetify-google-autocomplete, but nothing heppens
Here is my html

`            <vuetify-google-autocomplete
        append-icon="search"
        :clearable="true"
        :country="['PL']"
        :rules="rules"
        :disabled="disabled"
        :validateOnBlur="true"
        :enable-geolocation="false"
        label="Wyszukaj adres"
        :required="true"
        v-on:placechanged="onPlaceChanged">
      </vuetify-google-autocomplete>`

**Comment by mickaelchanrion** [comment]
Hi, the same for me!
In addition, I use vee-validate for validation. If I add vee-validate props, then the app crashes (not responding) :/
Do you have any idea @MadimetjaShika?

An example:
```pug
vuetify-google-autocomplete(
  id="gmap_autocomplete"
  name="address"
  label="Address"
  required
  v-validate="'required'"
  :error-messages="errors.collect('address')"
  @placechanged="getAddressData")
```

**Comment by timothynott** [comment]
I solved this by populating a hidden field with results and applying validation to the hidden field.

**Comment by kstraszewski** [comment]
@timothynott Can you show an example?

**Comment by MadimetjaShika** [comment]
Hi everyone. This is a rather odd issue. I'll look into getting it resolved.

**Comment by timothynott** [comment]
Sure. Tough to do a code example without a full publish, but the basic premise is using your placechanged callback to populate a hidden text element and having applying validation to that field.

Here's some example markup that would be in your template:

    <vuetify-google-autocomplete
        v-on:placechanged="googleStreetAddress"
        v-on:no-results-found="noGoogleStreetAddress"
        v-model="vgaHolder"
    >
    <v-text-field required v-model="googleAddress" v-show="false"></v-text-field>

And then you have script containing:

    data() {
        return {
            googleAddress: ''
        }
    },
    methods: {
        googleStreetAddress: function (data) {
            this.googleAddress = data.name // arbitrary -- could just by '1'
        },
        noGoogleStreetAddress: function (data) {
            this.googleAddress = ''
        }
    }

I like to show the data returned so one way to do that would be to have it fill a text field that is visible, but can't be edited.

**Comment by MadimetjaShika** [comment]
@kstraszewski could you please post your script file, particularly the value you're passing to the ``rules`` prop. I am able to get validation via the rules prop (with validate-on-blur set to true) working correctly using the example app and setup similar to yours (see gif below). Also, which version of the library are you using?

```html
<vuetify-google-autocomplete
  :id="id"
  :country="country"
  :label="labelText"
  :rules="[rules.required]"
  :validate-on-blur="true"
  :types="types"
  @placechanged="getAddressData"
  @no-results-found="noResultsFound"
  >
</vuetify-google-autocomplete>
```

```javascript
rules: {
  required: (value) => !!value || 'Required.',
}
```

![vga_validation_on_blur](https://user-images.githubusercontent.com/6643245/41063841-2220d53c-69da-11e8-9b75-3e0c0473e4af.gif)

@Michkkael I haven't checked if integration with vee-validate or vuelidate works as expected. I'll look into this for you and let you know when it's sorted.
