### ISSUE TITLE
Disable spellcheck

### ISSUE THREAD

**Issue by ledermann** [MadimetjaShika/vuetify-google-autocomplete#52]
`spellcheck` should be disabled for the corresponding `input` to remove the dotted red line in this example (screenshot taken in Chrome on macOS):

<img width="574" alt="disable-autocorrect" src="https://user-images.githubusercontent.com/3557/42751176-34c556f2-88ea-11e8-8e48-88c22f89b209.png">

And, while you're at it, `autocorrect` and some other attributes of the `input` element should be disabled, too:
https://davidwalsh.name/disable-autocorrect

**Comment by MadimetjaShika** [comment]
Hi @ledermann ,

Thanks for posting this issue. I do apologise for taking very long to address this.

This should be resolved in the next release, ``v2.0.0-beta.5``, and should be published within the next hour or two.

Please do let me know if you still experience issues.

**Comment by ledermann** [comment]
`v2.0.0-beta.5` works fine, thank you!
