### ISSUE TITLE
Include all types

### ISSUE THREAD

**Issue by Kelf2610** [MadimetjaShika/vuetify-google-autocomplete#54]
The **types** prop works just fine, and you can change it to 'address', establishment, (regions) and etc.
However, is there a way to include multiple types?

**Comment by MadimetjaShika** [comment]
Hi @kelflame2610,

According to the [Google Places Docs](https://developers.google.com/places/supported_types#table3),

> If nothing is specified, all types are returned. In general only a single type is allowed. The exception is that you can safely mix the geocode and establishment types, but note that this will have the same effect as specifying no types

Hope that answers your question. Will close this issue for now, feel free to re-open if I did not answer your question.
