### ISSUE TITLE
No drop down to choose locations

### ISSUE THREAD

**Issue by redhedded1** [MadimetjaShika/vuetify-google-autocomplete#55]
Using this on a SPA built with Vue CLI 3. Neither stable version supplies a dropdown of choices. 

On further investigation, none of the vuetify components using dropdowns (select, datatable, etc.) show the drop down or show it absurdly displaced away from the component.

Too bad, both Vuetify and this package would be stellar if they were usable (due to the dropdown issue).

**Comment by SzymonKrysztofiak** [comment]
I have a problem with this lib on Vue CLI 3. I need to reload my SPA site every single time when i want to type some place. Otherwise it doesn't work... Any suggestions?

**Comment by redhedded1** [comment]
I'll close this out of lack of concern from anyone.

**Comment by MadimetjaShika** [comment]
Hi Larry,

Thanks for posting this. Unfortunately I’m unable to have a proper look at
this at the moment, and will only get a chance to investigate properly
within the week or so. If you do have a solution, please make a PR and I’ll
be happy to merge if all is well.

Apologies for my delayed responses. 🙏🏾
