### ISSUE TITLE
Once a place is selected, can the search text be replaced by the selected place?

### ISSUE THREAD

**Issue by yeedle** [MadimetjaShika/vuetify-google-autocomplete#6]
In @olefirenko's version, once a place is selected from the dropdown, the text in the search bar changes to the selected place. However, in this version, even after a place is selected, when the search bar is clicked, the original search text is still there. Is it possible to change this behavior?

**Comment by MadimetjaShika** [comment]
Hi @yeedle! Thanks for pointing this out. The autocomplete text was only being emitted and not actually being updated on the component, but I noticed a recent update was made to the original fork to resolve this, so I just pulled those changes in. All should be good now.

Cheers!

**Comment by yeedle** [comment]
Thanks! Awesome work!
