### ISSUE TITLE
Language option

### ISSUE THREAD

**Issue by ComeWllt** [MadimetjaShika/vuetify-google-autocomplete#65]
Would it be possible to add a language option, as it is supported by the Google Maps API?

https://maps.googleapis.com/maps/api/js?key=API_KEY&libraries=places&language=LANGUAGE

```
Vue.use(VuetifyGoogleAutocomplete, {
  apiKey: API_KEY,
  language: LANGUAGE
});
```

**Comment by MadimetjaShika** [comment]
Hi there,

Thanks for this. It definitely will be possible. You're welcome to make a PR if you'd like, otherwise i'll look into this within the week.

**Comment by ComeWllt** [comment]
Hi,

I've submitted this pull request [#69](https://github.com/MadimetjaShika/vuetify-google-autocomplete/pull/69)

This is the first PR I submit so don't hesitate to tell me if I forgot something 🙂

Thank you!

**Comment by MadimetjaShika** [comment]
Hi,

Thanks for the PR. Sorry i've taken so long to merge.
