### ISSUE TITLE
prepend-inner-icon is not working

### ISSUE THREAD

**Issue by pkundis** [MadimetjaShika/vuetify-google-autocomplete#72]
If I try to use "prepend-inner-icon" for <vuetify-google-autocomplete> component. 
Icon is not working/visible. I saw your @MadimetjaShika previous fix for "prepend-icon" https://github.com/MadimetjaShika/vuetify-google-autocomplete/issues/20 which works great, but "prepend-inner-icon" is missing in that file.

**Comment by adrielgro** [comment]
I have the same problem, thx

**Comment by MadimetjaShika** [comment]
Hi, support for ``prepend-inner-icon`` has been added in vuetify-google-autocomplete``v2.0.0``, along with all new vuetify ``v2.1.*`` props.

Feel free to re-open this issue if you still experience problems.
