### ISSUE TITLE
Return city - administrative_area_level_2 field

### ISSUE THREAD

**Issue by AlissonRS** [MadimetjaShika/vuetify-google-autocomplete#74]
Google Places API has this field `administrative_area_level_2` in the response object which usually represents the city of the place. This component is already returning `administrative_area_level_1` which stands for the state/province. It would be really helpful if you returned this field as well.

Reference:

[Google Places API Docs](https://developers.google.com/places/web-service/autocomplete)

**Comment by MadimetjaShika** [comment]
Hi @AlissonRS, this should be resolved in ``v2.0.0`` of this library.

Both ``administrative_area_level_1`` and ``administrative_area_level_2`` are available in the result object now.

<img width="1680" alt="Screenshot 2019-12-31 at 15 11 39" src="https://user-images.githubusercontent.com/6643245/71622657-fd901100-2bdf-11ea-8367-0ccf13a7685d.png">

Please feel free to re-open this issue if you still get trouble with this.
