### ISSUE TITLE
This repo seems to be abandoned

### ISSUE THREAD

**Issue by egeersoz** [MadimetjaShika/vuetify-google-autocomplete#80]
Last update was all the way back in April (Vuetify 2 came out since then) and the demo page doesn't seem to work.

**Comment by PabloGBarcelo** [comment]
Im using and works great. 0 problems except that not have debounce.

**Comment by MadimetjaShika** [comment]
Hi @egeersoz. I'd unfortunately neglected this library and haven't been able to update it as frequently as I would have liked. I am however planning to fully enable support for the latest Vuetify sometime during December, along with other vue-cli 3 based updates.

Is your comment a request for Vuetify 2.* support? And thanks for the demo-page heads up, it's back up now.

PS - While contributions are welcome via PRs, it would be awesome if I had folk to help me maintain this library :)
