### ISSUE TITLE
Props Outline not working.

### ISSUE THREAD

**Issue by Sebarkar** [MadimetjaShika/vuetify-google-autocomplete#87]
Props Outline not working.

In Vuetify it's Outlined.

**Comment by MadimetjaShika** [comment]
Hi, unfortunately, I can't help you if you don't provide sufficient information. Please elaborate on your implementation, e.g. share code of your usage. What version of this library are you using? What version of Vuetify are you using?

**Comment by Sebarkar** [comment]
Thank you MadimetjaShika for quick response.

<vuetify-google-autocomplete
                    id="map"
                    ref="address"
                    :outline="true"
                    :types="types"
                    append-icon="search"
                    placeholder=""
                    :label="$t('accommodation.enter location')"
                    @placechanged="getFields"
                    country="ua"
                />

And :outline="true" not working as well.

I'm using "vuetify-google-autocomplete": "^2.0.0-beta.8" with "vuetify": "^2.1.6".

**Comment by MadimetjaShika** [comment]
Vuetify ``v2.*`` supports a new prop called ``outlined``, which is different to the one supported in previous versions, ``outline`` (notice the **d**), which this library supports.

This library does not yet support all features of the latest Vuetify ``v2.*``. I'm planning on incorporating full support during December 2019, and will thereafter release an official v2 version inline with the official Vuetify versions.

Example with Vuetify ``v1.5.*`` and vuetify-google-autocomplete ``2.0.0-beta.8`` using the ``outline`` prop.
<img width="1680" alt="Screenshot 2019-11-20 at 23 04 16" src="https://user-images.githubusercontent.com/6643245/69278016-1e7d4380-0bea-11ea-8d4a-aade3fa26228.png">

**Comment by Sebarkar** [comment]
Thanks for answer. Looking forward for new version :)
