### ISSUE TITLE
enhancement suggestion: separate label from placeholder

### ISSUE THREAD

**Issue by jess8bit** [MadimetjaShika/vuetify-google-autocomplete#9]
I think it would be could to have two separate props for label and placeholder as it is in vuetify v-text-field, instead of having one merged into both, so that we can benefit from the animation that pushes a minimized label on top of the input field, if you see what I mean.

It would help to have a more consistent presentation when one integrate this component in a list of other v-text-fields.

thanks!

**Comment by MadimetjaShika** [comment]
Hi @jesswa. Thanks for your suggestion, it does make sense and I'm happy with it. I should get a chance to make this change for you within the week, however if you'd like it sooner you're welcome to make a PR for the change and i'll merge it in.

**Comment by jess8bit** [comment]
thanks for considering this proposal!
no rush :)

**Comment by MadimetjaShika** [comment]
@jesswa the enhancement has been merged and published to npm on v1.1.0. This updates the component to match vuetify text fields as at v.0.16.9.

Thanks again!

**Comment by jess8bit** [comment]
awesome! just tested, thank you!
